-- phase: expand
-- OpenVibe.Search on PostgreSQL (ADR-035, roadmap WS-X2): the tables as they were on SQLite (converted by openvibe-sdk
-- tools/asyncify/sqlite-schema-to-pg: text COLLATE "C" compares like SQLite, integers are bigint, identities keep their ids),
-- then the openvibe-publishing stores and the openvibe-sdk inbox and outbox. Generated once on 2026-09-28; never edited after it runs.

CREATE TABLE documents (
    rid               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner             text COLLATE "C" NOT NULL,
    type              text COLLATE "C" NOT NULL,
    id                text COLLATE "C" NOT NULL,
    revision          bigint NOT NULL,
    deleted           bigint NOT NULL DEFAULT 0,
    visibility        text COLLATE "C",
    publication_state text COLLATE "C",
    exposure          bigint NOT NULL DEFAULT 0,   -- document.js EXPOSURE (0 none .. 3 public listed)
    index_decision    text COLLATE "C" NOT NULL,
    noindex_reasons   text COLLATE "C" NOT NULL DEFAULT '[]',
    canonical_url     text COLLATE "C",
    title             text COLLATE "C",
    language          text COLLATE "C",
    published_at      text COLLATE "C",
    updated_at        text COLLATE "C",
    sort_at           text COLLATE "C" NOT NULL DEFAULT '',     -- updated_at, else published_at: browse order
    doc               text COLLATE "C" NOT NULL,                -- normalized document JSON (tombstone: identity only)
    hash              text COLLATE "C" NOT NULL,
    via               text COLLATE "C" NOT NULL,                -- event | api
    event_id          text COLLATE "C",
    indexed_at        bigint NOT NULL,
    UNIQUE (owner, type, id)
);
CREATE INDEX idx_documents_exposure ON documents (exposure, sort_at, rid);
CREATE INDEX idx_documents_owner ON documents (owner, type, id);

-- ACL keys of servable non-public documents: kind s = subject, g = group, e = entitlement.
CREATE TABLE doc_acl (
    rid   bigint NOT NULL,
    kind  text COLLATE "C" NOT NULL CHECK (kind IN ('s', 'g', 'e')),
    value text COLLATE "C" NOT NULL,
    PRIMARY KEY (rid, kind, value)
);
CREATE INDEX idx_doc_acl_value ON doc_acl (kind, value, rid);

CREATE TABLE doc_facets (
    rid   bigint NOT NULL,
    key   text COLLATE "C" NOT NULL,
    value text COLLATE "C" NOT NULL,
    PRIMARY KEY (rid, key, value)
);
CREATE INDEX idx_doc_facets_value ON doc_facets (key, value, rid);

-- Inbox: one receipt per consumed event (exactly-once effects), with what happened.
CREATE TABLE idempotency_receipts (
    consumer     text COLLATE "C" NOT NULL,
    event_id     text COLLATE "C" NOT NULL,
    outcome      text COLLATE "C" NOT NULL,
    processed_at bigint NOT NULL,
    PRIMARY KEY (consumer, event_id)
);

-- Index-document events Search refused (bad document, wrong owner, subject mismatch). Owners
-- read their own through GET /api/v1/owners/:owner/rejections.
CREATE TABLE ingest_rejections (
    seq        bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id   text COLLATE "C" NOT NULL,
    event_type text COLLATE "C",
    owner      text COLLATE "C",
    type       text COLLATE "C",
    id         text COLLATE "C",
    revision   bigint,
    code       text COLLATE "C" NOT NULL,
    detail     text COLLATE "C",
    at         bigint NOT NULL
);
CREATE INDEX idx_ingest_rejections_owner ON ingest_rejections (owner, seq);

-- server/events/outbox.js ensureSchema()
CREATE TABLE event_outbox (
    seq             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id        text COLLATE "C" NOT NULL UNIQUE,
    event_type      text COLLATE "C" NOT NULL,
    envelope        text COLLATE "C" NOT NULL,
    created_at      bigint NOT NULL,
    attempts        bigint NOT NULL DEFAULT 0,
    next_attempt_at bigint NOT NULL DEFAULT 0,
    sent_at         bigint,
    rejected_at     bigint,
    last_error      text COLLATE "C"
);
CREATE INDEX idx_event_outbox_due ON event_outbox(sent_at, rejected_at, next_attempt_at);

-- server/purge.js ensureSchema()
CREATE TABLE removals (
    seq               bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id          text COLLATE "C" NOT NULL,              -- the search.document.removed event
    owner             text COLLATE "C" NOT NULL,
    type              text COLLATE "C" NOT NULL,
    id                text COLLATE "C" NOT NULL,
    revision          bigint NOT NULL,
    reason            text COLLATE "C" NOT NULL,
    previous_exposure text COLLATE "C" NOT NULL,
    exposure          text COLLATE "C" NOT NULL,
    canonical_url     text COLLATE "C",                       -- only a URL that had been public
    at                bigint NOT NULL
);
CREATE INDEX idx_removals_owner ON removals (owner, seq);

CREATE TABLE cdn_purges (
    seq             bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    removal_seq     bigint NOT NULL,
    provider        text COLLATE "C" NOT NULL DEFAULT 'cloudflare',
    zone_id         text COLLATE "C",
    url             text COLLATE "C" NOT NULL,
    state           text COLLATE "C" NOT NULL CHECK (state IN ('pending', 'purged', 'failed', 'skipped')),
    detail          text COLLATE "C",
    attempts        bigint NOT NULL DEFAULT 0,
    next_attempt_at bigint NOT NULL DEFAULT 0,
    created_at      bigint NOT NULL,
    done_at         bigint
);
-- One pending purge per URL: a sitemap shared by many removals is purged once per batch.
CREATE UNIQUE INDEX idx_cdn_purges_pending ON cdn_purges (zone_id, url) WHERE state = 'pending';
CREATE INDEX idx_cdn_purges_due ON cdn_purges (state, next_attempt_at, seq);

-- server/saved.js ensureSchema()
CREATE TABLE saved_searches (
    id           text COLLATE "C" PRIMARY KEY,
    subject      text COLLATE "C" NOT NULL,                  -- usr_… (the person who saved it)
    name         text COLLATE "C" NOT NULL,
    q            text COLLATE "C" NOT NULL DEFAULT '',
    filters      text COLLATE "C" NOT NULL,                  -- canonical JSON {owner,type,language,facets}
    query_hash   text COLLATE "C" NOT NULL,                  -- same query saved twice = one row
    created_at   bigint NOT NULL,
    updated_at   bigint NOT NULL,
    last_run_at  bigint,
    UNIQUE (subject, query_hash)
);
CREATE INDEX idx_saved_searches_subject ON saved_searches (subject, created_at);

-- The full-text index (server/engine/pg.js): one row per servable document, split by audience (exposure 3 public
-- listed: all an anonymous query ever reads; 1 restricted: ACL-checked in the same SQL). Drafts, unpublished, deleted
-- and noindex documents have no row. Title, summary and body carry weights A, B and C. Derived from documents.doc and
-- rebuilt at boot when its counts disagree with the documents table (after the one-time import, for instance).
CREATE TABLE search_fts (
    rid       bigint PRIMARY KEY REFERENCES documents(rid) ON DELETE CASCADE,
    audience  bigint NOT NULL,
    fresh_at  bigint,                                   -- epoch ms of published_at, else updated_at (the freshness boost)
    title     text NOT NULL,
    summary   text NOT NULL,
    body      text NOT NULL,
    tsv       tsvector NOT NULL
);
CREATE INDEX search_fts_tsv ON search_fts USING gin (tsv);
CREATE INDEX search_fts_audience ON search_fts (audience, rid);
